### ISSUE TITLE
Adding if-let, when-let, cond-let, etc?

### ISSUE THREAD

**Issue by AlexKnauth** [jsmaniac/anaphoric#1]
Should hygienic versions of these anaphoric macros be provided as well, where the user would specify an identifier to bind?

``` racket
(if-let [x (member 'a lst)]
  (displayln x)
  (displayln "not found"))
```

``` racket
(when-let [x (member 'a lst)]
  (displayln x))
```

``` racket
(cond-let
  [[x (member 'a lst)] (displayln x)]
  [[x (member 'b lst)] (displayln x)]
  [else (displayln "not found")])
```

The syntax-parameter versions, `aif`, `awhen`, and `acond`, would have straightforward translations into these + `syntax-parameterize`.

``` racket
(define-syntax-rule (aif condition true-branch false-branch)
  (if-let [tmp condition]
    (syntax-parameterize ([it (make-rename-transformer #'tmp)])
      true-branch)
    false-branch))
```

``` racket
(define-syntax-rule (awhen condition . body)
  (when-let [tmp condition]
    (syntax-parameterize ([it (make-rename-transformer #'tmp)])
      . body)))
```

``` racket
(define-syntax acond
  (syntax-parser #:literals (else)
    [(acond [condition . body] ... [else . else-body])
     #'(cond-let
         [[tmp condition]
          (syntax-parameterize ([it (make-rename-transformer #'tmp)])
            . body)]
         ...
         [else . else-body])]
    [(acond [condition . body] ...)
     #'(cond-let
         [[tmp condition]
          (syntax-parameterize ([it (make-rename-transformer #'tmp)])
            . body)]
         ...)]
```

**Comment by SuzanneSoy** [comment]
Sorry about the delay, for some reason GitHub didn't notify me about this issue. I added the `if-let`, `when-let` and `cond-let` (with a shorthand for `cond-let` where you need specify only one identifier). I didn't change the implementation of `aif`, `awhen` and `acond`, though, as it was rather short and simple anyway.

**Comment by AlexKnauth** [comment]
They wouldn't be shorter and simpler in terms of the `-let` versions?

**Comment by SuzanneSoy** [comment]
@AlexKnauth The code you suggested is shorter by one line, and looks nearly the same (`(let ([tmp c]) (if …))` instead of `(if-let (tmp c) …)`), so no big deal. Also, the extra level of indirection wouldn't improve readability. I did reuse part of your acond code to implement cond-let, though :) .

**Comment by AlexKnauth** [comment]
Okay

**Comment by SuzanneSoy** [comment]
Hi @AlexKnauth ! In order to match the current Racket relicensing, I'm changing the license for all my project to LGPL + MIT + Apache 2 + CC0 (to cover any potential future license change).

Since you contributed some code, is that okay for you concerning this project?

Thanks,
Georges Dupéron

**Comment by AlexKnauth** [comment]
Yes.

**Comment by SuzanneSoy** [comment]
Thanks!
